[book]
authors = ["bresilla"]
language = "en"
multilingual = false
src = "book/src"
title = "libvine Book"

[build]
build-dir = "book/build"

[output.html]
default-theme = "navy"
git-repository-url = ""
site-url = "/"
